name: Frontend CI

on:
  push:
    branches: [Eleanor/CI-#154]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Dev
        run: vite

      - name: Build
        run: pnpm exec vite build

      - name: Preview
        run: vite preview

      - name: Lint Check
        run: pnpm exec eslint . || true

      - name: Format Check
        run: pnpm run format

      - name: Test
        run: vitest run

      - name: Test:watch
        run: vitest

      - name: Test:ui
        run: vitest --ui
        
      - name: Test:coverage
        run: vitest run --coverage
        
      - name: Storybook
        run: storybook dev -p 6006  
        
      - name: Build-storybook
        run: storybook build

      

